### ISSUE TITLE
AttributeError: module 'posenet' has no attribute 'converter

### ISSUE THREAD

**Issue by KanzaRomman** [rwightman/posenet-python#15]
the files named **image_demo.py** and **webcam_demo.py** both are giving this error upon re-running.
`Reloaded modules: posenet, posenet.constants, posenet.decode_multi, posenet.decode, posenet.model, posenet.converter.config, posenet.utils
Traceback (most recent call last):

  File "<ipython-input-2-47e35424064a>", line 1, in <module>
    runfile('E:/spyder projects/posenet-python-master/posenet-python-master/arg_free_webcam_demo.py', wdir='E:/spyder projects/posenet-python-master/posenet-python-master')

  File "E:\Users\kanza\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 668, in runfile
    execfile(filename, namespace)

  File "E:\Users\kanza\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "E:/spyder projects/posenet-python-master/posenet-python-master/arg_free_webcam_demo.py", line 25, in <module>
    model_cfg, model_outputs = posenet.load_model(model, sess)

  File "E:\spyder projects\posenet-python-master\posenet-python-master\posenet\model.py", line 39, in load_model
    model_cfg = load_config(model_ord)

  File "E:\spyder projects\posenet-python-master\posenet-python-master\posenet\model.py", line 25, in load_config
    converter_cfg = posenet.converter.config.load_config()

AttributeError: module 'posenet' has no attribute 'converter'`

however, both work fine when ran for the first time, and also when they are run after restarting kernel or restarting ipython console.
can not understand the issue.
I tried to import the "converter" stuff in __init__.py, but didn't work.

**Comment by rwightman** [comment]
I've only tried running as a script, not in a notebook type environment. You're welcome to debug it but I don't plan to. You could always run as a script to make the conversion happen, then grab the converted model files, place in a fixed path relative to your notebook setup, then change the code to reference that location and remove the on-the-fly conversion import and execution.

**Comment by srego** [comment]
Use sys.path.insert(0, CONVERTER_DIR) to insert the path to the converter folder.
