### ISSUE TITLE
does it work on windows 10?

### ISSUE THREAD

**Issue by azarkiel** [rwightman/posenet-python#37]
I'm newbie on tensorflow and pose estimation.
I just followed all the steps described on main info.
Before that I created a conda environment to isolate the project.
Also I downloaded image folder with get_test_images.py script.

But when I execute both demos (image_demo.py and webcam_demo.py) terminal says:
AttributeError: module 'tensorflow' has no attribute 'Session'

I've tried these commands:
python image_demo.py --model 101 --image_dir ./images --output_dir ./output
python webcam_demo.py

I've got this on terminal:
2021-06-02 13:53:01.569440: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
Traceback (most recent call last):
  File "image_demo.py", line 74, in <module>
    main()
  File "image_demo.py", line 21, in main
    with tf.Session() as sess:
AttributeError: module 'tensorflow' has no attribute 'Session'

And for webcam_demo:
2021-06-02 13:55:10.650564: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
Traceback (most recent call last):
  File "webcam_demo.py", line 66, in <module>
    main()
  File "webcam_demo.py", line 19, in main
    with tf.Session() as sess:
AttributeError: module 'tensorflow' has no attribute 'Session'

The related package versions that I have installed are:
tensorboard                  2.4.0          pyhc547734_0
tensorboard-plugin-wit    1.6.0      py_0
tensorflow                    2.1.0           gpu_py36h3346743_0
tensorflow-base           2.1.0           gpu_py36h55f5790_0
tensorflow-estimator   2.5.0           pyh7b7c402_0
tensorflow-gpu            2.1.0           h0d30ee6_0
cudatoolkit                  10.1.243      h74a9793_0
cudnn                           7.6.5           cuda10.1_0
python                          3.6.13         h3758d61_0
opencv-python             3.4.5.20      pypi_0  

PD: I have got an GTX 1060 on my laptop.

Any suggestion?

**Comment by federicofusco** [comment]
What version of tensorflow are you using?

**Comment by Yash-Git-Hub** [comment]
tf.disable_v2_behavior() use this at the start i think you are using tensorflow 2.0>

**Comment by Yash-Singh-Pathania** [comment]
tf.compat.v1.Session() 
 use this rather than tf.session() 
For tensorflow model above 2.0
